### ISSUE TITLE
Json exception since upgrade from 2.1.3 to 3.0.2

### ISSUE THREAD

**Issue by JuEocene** [ArnoldV/Our.Umbraco.GMaps#179]
Hello,

A few days ago, we upgraded Umbraco from version 10 to 13. As part of this, we also updated Umbraco GMaps. Since then, we've encountered some issues.

When trying to access a page that uses a doctype with a GMaps property, we receive the following error:
**JsonException: The JSON value could not be converted to System.Nullable`1[Our.Umbraco.GMaps.Models.MapType].**

I have attempted several fixes, including:

Removing the custom map style JSON.
Changing the map type from "styled map" to "roadmap," "hybrid," "satellite," and "terrain."
Unfortunately, none of these worked, and they also made the application unstable. I encounter the following error:

**ModelBindingException: Cannot bind source content type Umbraco.Cms.Web.Common.PublishedModels.Homepage to model type Umbraco.Cms.Web.Common.PublishedModels.Master. Both view and content models are in-memory generated, with different versions. The application is in an unstable state and should be restarted.**

This forces me to restart the application to recover.

Would you have any insight into what might be causing these issues, or potential solutions?

Thank you for your help!

**Comment by imZEH** [comment]
I'm getting similar issue. by any chance , Have you found any fixes for this ?

**Comment by imZEH** [comment]
I have done several troubleshooting and got me into attaching the package source code and from there found out that the old JSON data we have from upgrading Umbraco version doesn't correctly parse the JSON data. From there you can  modify the source code to parse the JSON that suites your needs.

**Comment by JuEocene** [comment]
Hi,
No, I haven't found a way to fix it yet.
I just downgraded the GMaps version to 2.1.3, and fortunately, it works with Umbraco 13.
Thanks for your suggestion for the fix. I'll try it asap.

**Comment by robertjf** [comment]
We've just pushed up a new version (3.0.3) to NuGet, with some changes that should fix issues with the MapType legacy data.  I'll close this but if you still see this as a problem, feel free to re-open it and please supply an example of the offending JSON data.

**Comment by Myster** [comment]
I still get this issue in 3.0.5
This is an upgrade project the legacy version was 1.3.1
the json looks like this (part of the PostSave payload):

```
 {
                    "id": 981769,
                    "alias": "bodyControls",
                    "value": [
                        {
                            "key": "aaf5caa6-800f-46c8-82c9-9e00ea2dda75",
                            "name": "Map",
                            "ncContentTypeAlias": "googleMap",
                            "anchor": "",
                            "heading": "__redacted__",
                            "title": "__redacted__",
                            "map": {
                                "address": {
                                    "full_address": "109 __redacted__ 1023, New Zealand",
                                    "streetNumber": "109",
                                    "street": "__redacted__",
                                    "postalcode": "1023",
                                    "state": "Auckland",
                                    "city": "Auckland",
                                    "country": "New Zealand",
                                    "coordinates": {
                                        "lat": -36.00000647,
                                        "lng": 174.0006
                                    }
                                },
                                "mapconfig": {
                                    "zoom": 17,
                                    "maptype": "styled_map",
                                    "centerCoordinates": {
                                        "lat": -36.000058161908216,
                                        "lng": 174.00005104999996
                                    }
                                }
                            }
                        }
                    ]
                },
```

System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[Our.Umbraco.GMaps.Models.MapType]. Path: $.mapconfig.maptype | LineNumber: 0 | BytePositionInLine: 316.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String enumString)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Our.Umbraco.GMaps.PropertyValueConverter.SingleMapPropertyValueConverter.ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, Object inter, Boolean preview)
   at Umbraco.Cms.Core.PublishedCache.PublishedElementPropertyBase.GetValue(String culture, String segment)
   at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback publishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.PublishedElementExtensions.Value[T](IPublishedElement content, IPublishedValueFallback publishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at DXP.ModelsBuilder.GoogleMap.get_Map() in /home/runner/work/__redacted__/__redacted__/DXP/ModelsBuilder/umbraco/GoogleMap.generated.cs:line 66
   at AspNetCoreGeneratedDocument.Views_Partials_Elements_GoogleMap.ExecuteAsync() in /home/runner/work/__redacted__/__redacted__/DXP/Views/Partials/Elements/GoogleMap.cshtml:line 12
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
